### ISSUE TITLE
Problems with `as` prop typing

### ISSUE THREAD

**Issue by chaance** [modulz/design-system#15]
*EDIT*: It looks like headings *are* configurable via the `as` prop, but typing appears to be broken.

The following code throws a type warning.

```
<Subtitle css={{ mt: '$2', mb: '$5' }} as="p">
  Hello
</Subtitle>
```

The warning is fo the `as` prop.

```
Type '"p"' is not assignable to type '"span"'.
```

**Comment by peduarte** [comment]
Closing this since Radix is being deprecated. Moved to https://github.com/radix-ui/radix-legacy
